import { PROCEDURAL_ASSETS } from '../geometry/assets'
import type { AssetConfig } from '../types'

/** RM EYE particle typography — centered above headline panel */
export const RM_EYE_POSITION: [number, number, number] = [0, 1.35, -0.15]

export const ASSET_CONFIGS: AssetConfig[] = [
  {
    id: 'power-transformer',
    name: 'Power Transformer',
    label: 'Power Transformer',
    position: [-2.9, 0.55, -1.2],
    rotation: [0, 0.55, 0],
    scale: 1.25,
    particleDensity: 1.2,
    idleOpacity: 0.22,
    hoverIntensity: 0.45,
    connectionTarget: 'rm-eye',
    depthLayer: 'foreground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['power-transformer'].hitbox,
    labelPosition: { left: '8%', top: '18%' },
  },
  {
    id: 'dry-type-transformer',
    name: 'Dry-Type Transformer',
    label: 'Dry-Type Transformer',
    position: [-3.1, -0.15, -1.8],
    rotation: [0, 0.4, 0],
    scale: 0.72,
    particleDensity: 0.85,
    idleOpacity: 0.2,
    hoverIntensity: 0.42,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['dry-type-transformer'].hitbox,
    labelPosition: { left: '6%', top: '42%' },
  },
  {
    id: 'power-cables',
    name: 'Power Cables',
    label: 'Power Cables',
    position: [-2.6, -1.35, -1.5],
    rotation: [0, 0.35, 0.05],
    scale: 0.68,
    particleDensity: 0.8,
    idleOpacity: 0.19,
    hoverIntensity: 0.4,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['power-cables'].hitbox,
    labelPosition: { left: '10%', top: '72%' },
  },
  {
    id: 'gis',
    name: 'Gas Insulated Switchgear',
    label: 'GIS',
    position: [-1.05, 0.95, -2.2],
    rotation: [0, 0.25, 0],
    scale: 0.82,
    particleDensity: 0.95,
    idleOpacity: 0.21,
    hoverIntensity: 0.43,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS.gis.hitbox,
    labelPosition: { left: '28%', top: '14%' },
  },
  {
    id: 'circuit-breaker',
    name: 'Circuit Breaker',
    label: 'Circuit Breaker',
    position: [1.15, 0.85, -2.0],
    rotation: [0, -0.3, 0],
    scale: 0.78,
    particleDensity: 0.9,
    idleOpacity: 0.21,
    hoverIntensity: 0.43,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['circuit-breaker'].hitbox,
    labelPosition: { left: '62%', top: '16%' },
  },
  {
    id: 'rotating-machine',
    name: 'Rotating Machine',
    label: 'Rotating Machine',
    position: [2.85, 0.65, -2.2],
    rotation: [0, -0.55, 0],
    scale: 0.88,
    particleDensity: 0.9,
    idleOpacity: 0.2,
    hoverIntensity: 0.42,
    connectionTarget: 'rm-eye',
    depthLayer: 'foreground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['rotating-machine'].hitbox,
    labelPosition: { left: '78%', top: '20%' },
  },
  {
    id: 'ais',
    name: 'Air Insulated Switchgear',
    label: 'AIS',
    position: [3.0, -0.25, -2.8],
    rotation: [0, -0.5, 0],
    scale: 0.75,
    particleDensity: 0.85,
    idleOpacity: 0.19,
    hoverIntensity: 0.4,
    connectionTarget: 'rm-eye',
    depthLayer: 'background',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS.ais.hitbox,
    labelPosition: { left: '80%', top: '48%' },
  },
  {
    id: 'capacitor-bank',
    name: 'Capacitor Bank',
    label: 'Capacitor Bank',
    position: [2.3, -1.4, -2.0],
    rotation: [0, -0.4, 0],
    scale: 0.65,
    particleDensity: 0.75,
    idleOpacity: 0.18,
    hoverIntensity: 0.38,
    connectionTarget: 'rm-eye',
    depthLayer: 'background',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['capacitor-bank'].hitbox,
    labelPosition: { left: '72%', top: '74%' },
  },
  {
    id: 'shunt-reactor',
    name: 'Shunt Reactor',
    label: 'Shunt Reactor',
    position: [0.35, -1.55, -2.5],
    rotation: [0, -0.15, 0],
    scale: 0.72,
    particleDensity: 0.85,
    idleOpacity: 0.19,
    hoverIntensity: 0.4,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['shunt-reactor'].hitbox,
    labelPosition: { left: '42%', top: '78%' },
  },
]
