import { PROCEDURAL_ASSETS } from '../geometry/assets'
import type { AssetConfig } from '../types'

/** RM EYE particle typography — centered above headline */
export const RM_EYE_POSITION: [number, number, number] = [0, 0.68, 0.1]

export const ASSET_CONFIGS: AssetConfig[] = [
  {
    id: 'power-transformer',
    name: 'Power Transformer',
    label: 'Power Transformer',
    position: [-3.4, 0.85, -2.0],
    rotation: [0, 0.52, 0],
    scale: 1.55,
    particleDensity: 1.2,
    idleOpacity: 0.42,
    hoverIntensity: 0.58,
    connectionTarget: 'rm-eye',
    depthLayer: 'foreground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['power-transformer'].hitbox,
    labelPosition: { left: '7%', top: '16%' },
  },
  {
    id: 'dry-type-transformer',
    name: 'Dry-Type Transformer',
    label: 'Dry-Type Transformer',
    position: [-3.2, 0.05, -2.4],
    rotation: [0, 0.42, 0],
    scale: 0.78,
    particleDensity: 0.9,
    idleOpacity: 0.4,
    hoverIntensity: 0.55,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['dry-type-transformer'].hitbox,
    labelPosition: { left: '5%', top: '44%' },
  },
  {
    id: 'power-cables',
    name: 'Power Cables',
    label: 'Power Cables',
    position: [-2.7, -1.15, -2.0],
    rotation: [0, 0.38, 0.05],
    scale: 0.72,
    particleDensity: 0.85,
    idleOpacity: 0.39,
    hoverIntensity: 0.53,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['power-cables'].hitbox,
    labelPosition: { left: '8%', top: '70%' },
  },
  {
    id: 'gis',
    name: 'Gas Insulated Switchgear',
    label: 'GIS',
    position: [-1.0, 1.15, -2.8],
    rotation: [0, 0.22, 0],
    scale: 0.88,
    particleDensity: 1.0,
    idleOpacity: 0.41,
    hoverIntensity: 0.56,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS.gis.hitbox,
    labelPosition: { left: '26%', top: '12%' },
  },
  {
    id: 'circuit-breaker',
    name: 'Circuit Breaker',
    label: 'Circuit Breaker',
    position: [1.0, 1.05, -2.6],
    rotation: [0, -0.28, 0],
    scale: 0.82,
    particleDensity: 0.95,
    idleOpacity: 0.41,
    hoverIntensity: 0.56,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['circuit-breaker'].hitbox,
    labelPosition: { left: '60%', top: '13%' },
  },
  {
    id: 'rotating-machine',
    name: 'Rotating Machine',
    label: 'Rotating Machine',
    position: [3.1, 0.85, -2.6],
    rotation: [0, -0.52, 0],
    scale: 0.95,
    particleDensity: 0.95,
    idleOpacity: 0.4,
    hoverIntensity: 0.55,
    connectionTarget: 'rm-eye',
    depthLayer: 'foreground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['rotating-machine'].hitbox,
    labelPosition: { left: '76%', top: '17%' },
  },
  {
    id: 'ais',
    name: 'Air Insulated Switchgear',
    label: 'AIS',
    position: [3.0, -0.05, -3.2],
    rotation: [0, -0.48, 0],
    scale: 0.82,
    particleDensity: 0.9,
    idleOpacity: 0.39,
    hoverIntensity: 0.53,
    connectionTarget: 'rm-eye',
    depthLayer: 'background',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS.ais.hitbox,
    labelPosition: { left: '78%', top: '46%' },
  },
  {
    id: 'capacitor-bank',
    name: 'Capacitor Bank',
    label: 'Capacitor Bank',
    position: [2.4, -1.15, -2.4],
    rotation: [0, -0.38, 0],
    scale: 0.7,
    particleDensity: 0.8,
    idleOpacity: 0.38,
    hoverIntensity: 0.51,
    connectionTarget: 'rm-eye',
    depthLayer: 'background',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['capacitor-bank'].hitbox,
    labelPosition: { left: '70%', top: '72%' },
  },
  {
    id: 'shunt-reactor',
    name: 'Shunt Reactor',
    label: 'Shunt Reactor',
    position: [0.15, -1.25, -2.8],
    rotation: [0, -0.12, 0],
    scale: 0.78,
    particleDensity: 0.9,
    idleOpacity: 0.39,
    hoverIntensity: 0.53,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['shunt-reactor'].hitbox,
    labelPosition: { left: '40%', top: '76%' },
  },
]
