import { PROCEDURAL_ASSETS } from '../geometry/assets'
import type { AssetConfig } from '../types'

/** RM EYE position — slightly right of center, deeper in scene */
export const RM_EYE_POSITION: [number, number, number] = [1.8, 0.2, -2.5]

export const ASSET_CONFIGS: AssetConfig[] = [
  {
    id: 'power-transformer',
    name: 'Power Transformer',
    position: [-4.2, -0.8, -1.2],
    rotation: [0, 0.4, 0],
    scale: 1.0,
    particleDensity: 1.1,
    idleOpacity: 0.3,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'foreground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['power-transformer'].hitbox,
  },
  {
    id: 'dry-type-transformer',
    name: 'Dry-Type Transformer',
    position: [-2.2, 1.5, -3.8],
    rotation: [0, -0.25, 0],
    scale: 0.85,
    particleDensity: 0.9,
    idleOpacity: 0.27,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'background',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['dry-type-transformer'].hitbox,
  },
  {
    id: 'gis',
    name: 'Gas Insulated Switchgear',
    position: [-0.5, 0.8, -3.2],
    rotation: [0, 0.2, 0],
    scale: 0.9,
    particleDensity: 1.0,
    idleOpacity: 0.3,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS.gis.hitbox,
  },
  {
    id: 'ais',
    name: 'Air Insulated Switchgear',
    position: [3.6, 0.5, -4.5],
    rotation: [0, -0.55, 0],
    scale: 0.85,
    particleDensity: 0.85,
    idleOpacity: 0.25,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'background',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS.ais.hitbox,
  },
  {
    id: 'circuit-breaker',
    name: 'Circuit Breaker',
    position: [1.2, -1.5, -1.6],
    rotation: [0, -0.15, 0],
    scale: 0.8,
    particleDensity: 0.95,
    idleOpacity: 0.3,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'foreground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['circuit-breaker'].hitbox,
  },
  {
    id: 'rotating-machine',
    name: 'Rotating Machine',
    position: [-0.5, -1.8, -2.5],
    rotation: [0, 0.35, 0],
    scale: 0.75,
    particleDensity: 0.9,
    idleOpacity: 0.28,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: true,
    hitbox: PROCEDURAL_ASSETS['rotating-machine'].hitbox,
  },
  {
    id: 'power-cables',
    name: 'Power Cables',
    position: [2.6, -1.3, -3.5],
    rotation: [0, -0.35, 0.05],
    scale: 0.75,
    particleDensity: 0.8,
    idleOpacity: 0.26,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'midground',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['power-cables'].hitbox,
  },
  {
    id: 'shunt-reactor',
    name: 'Shunt Reactor',
    position: [4.2, -0.4, -2.8],
    rotation: [0, -0.7, 0],
    scale: 0.7,
    particleDensity: 0.85,
    idleOpacity: 0.25,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'background',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['shunt-reactor'].hitbox,
  },
  {
    id: 'capacitor-bank',
    name: 'Capacitor Bank',
    position: [-1.0, 1.6, -4.8],
    rotation: [0, 0.3, 0],
    scale: 0.65,
    particleDensity: 0.75,
    idleOpacity: 0.24,
    hoverIntensity: 1,
    connectionTarget: 'rm-eye',
    depthLayer: 'background',
    mobileVisible: false,
    hitbox: PROCEDURAL_ASSETS['capacitor-bank'].hitbox,
  },
]
